on:
  push

jobs:
  job1:
    env:
      NAME: "Sarah"
      WORK: ${{env.WORK}}
    runs-on: ubuntu-latest
    steps:
      - name: Display variable
        run: |
          echo ${{env.NAME}}
          echo ${{WORK}}
