on:
  push

jobs:
  job1:
    env:
      ENV_NAME: "Harry"
    runs-on: ubuntu-latest
    steps:
      - name: Display variable
        run: |
          echo ${{env.ENV_NAME}}
          echo ${{vars.NAME}}
